export const data = [{
    "id": "1",
    "agente": "Agente Ejemplo",
    "departamento": "Amazonas",
    "participante": "Participante",
    "rotation": "82",
},
{
    "id": "2",
    "agente": "Agente Ejemplo",
    "departamento": "Ancash",
    "participante": "Participante",
    "rotation": "67",
},
{
    "id": "3",
    "agente": "Agente Ejemplo",
    "departamento": "Apurímac",
    "participante": "Participante",
    "rotation": "52",
},
{
    "id": "4",
    "agente": "Agente Ejemplo",
    "departamento": "Arequipa",
    "participante": "Participante",
    "rotation": "37",
},
{
    "id": "5",
    "agente": "Agente Ejemplo",
    "departamento": "Ayacucho",
    "participante": "Participante",
    "rotation": "22",
},
{
    "id": "6",
    "agente": "Agente Ejemplo",
    "departamento": "Cajamarca",
    "participante": "Participante",
    "rotation": "7",
},
{
    "id": "7",
    "agente": "Agente Ejemplo",
    "departamento": "Callao",
    "participante": "Participante",
    "rotation": "352",
},
{
    "id": "8",
    "agente": "Agente Ejemplo",
    "departamento": "Cusco",
    "participante": "Participante",
    "rotation": "337",
},
{
    "id": "9",
    "agente": "Agente Ejemplo",
    "departamento": "Huánuco",
    "participante": "Participante",
    "rotation": "322",
},
{
    "id": "10",
    "agente": "Agente Ejemplo",
    "departamento": "Ica",
    "participante": "Participante",
    "rotation": "307",
},
{
    "id": "11",
    "agente": "Agente Ejemplo",
    "departamento": "Junín",
    "participante": "Participante",
    "rotation": "292",
},
{
    "id": "12",
    "agente": "Agente Ejemplo",
    "departamento": "La Libertad",
    "participante": "Participante",
    "rotation": "277",
},
{
    "id": "13",
    "agente": "Agente Ejemplo",
    "departamento": "Lambayeque",
    "participante": "Participante",
    "rotation": "262",
},
{
    "id": "14",
    "agente": "Agente Ejemplo",
    "departamento": "Lima",
    "agente": "Red de AT Magdalena",
    "participante": "Bladimir Quispe",
    "rotation": "247",
},
{
    "id": "15",
    "agente": "Agente Ejemplo",
    "departamento": "Loreto",
    "participante": "Participante",
    "rotation": "232",
},
{
    "id": "16",
    "agente": "Agente Ejemplo",
    "departamento": "Madre de Dios",
    "participante": "Participante",
    "rotation": "217",
},
{
    "id": "17",
    "agente": "Agente Ejemplo",
    "departamento": "Moquegua",
    "participante": "Participante",
    "rotation": "202",
},
{
    "id": "18",
    "agente": "Agente Ejemplo",
    "departamento": "Pasco",
    "participante": "Participante",
    "rotation": "187",
},
{
    "id": "19",
    "agente": "Agente Ejemplo",
    "departamento": "Piura",
    "participante": "Participante",
    "rotation": "172",
},
{
    "id": "20",
    "agente": "Agente Ejemplo",
    "departamento": "Puno",
    "participante": "Participante",
    "rotation": "157",
},
{
    "id": "21",
    "agente": "Agente Ejemplo",
    "departamento": "San Martín",
    "participante": "Participante",
    "rotation": "142",
},
{
    "id": "22",
    "agente": "Agente Ejemplo",
    "departamento": "Tacna",
    "participante": "Ganador",
    "rotation": "127",
},
{
    "id": "23",
    "agente": "Agente Ejemplo",
    "departamento": "Tumbes",
    "participante": "Participante",
    "rotation": "112",
},
{
    "id": "24",
    "agente": "Agente Ejemplo",
    "departamento": "Ucayali",
    "participante": "Participante",
    "rotation": "97",
}];